"""
@Project : zabank_imc_case
@File    : example_test_za_zone_entry_page.py
@Author  : Auto Generated by API Test Generator
@Date    : 2026-03-13
"""
import allure
import pytest
from pytest_zati_base.utils.assertion import Assertion
from pytest_zati_base.utils import logging

from service.zabank_imc_activity_service import model


@allure.epic("ZA Zone活动")
@allure.feature("入口页查询")
class TestZaZoneEntryPage:
    """
    ZA Zone - 入口页查询接口测试类

    测试接口: /activity/zaZone/entryPage
    接口方法: POST
    接口说明: 查询ZA Zone活动入口页信息,包含用户参与状态、等级、进度等
    """

    @allure.title("正常场景-已参与用户查询")
    @allure.story("用户状态查询")
    @pytest.mark.data('za_zone/entry_page_01_joined.yaml')
    @pytest.mark.P0
    def test_entry_page_01_joined(self, activity_sc, data):
        """
        测试场景: 已参与用户查询活动状态

        前置条件:
        - 用户已完成ZA Zone活动注册
        - 用户账号状态正常
        - 用户有活动参与记录

        测试步骤:
        1. 构造已参与用户的请求参数(customer_no)
        2. 调用入口页查询接口
        3. 验证响应码为成功
        4. 验证返回活动状态信息

        预期结果:
        - code=IA0000
        - 返回用户参与信息
        - 包含活动状态和等级信息
        """
        # 步骤1: 获取测试数据(从tests列表的第一个case)
        step = data[0]

        # 步骤2: 构造请求
        user_id = step.get("user_id", "")
        header = {"userid": user_id, "language": "ca"}

        # ✅ 正确写法: 直接使用 model.{ModelClassName}() 实例化
        params = model.ActivityZaZoneEntryPage()
        params.json_data = {
            "customerNo": step.get("customer_no", "")
        }

        # 步骤3: 发送请求
        logging.info("测试已参与用户查询活动状态")
        resp = activity_sc.controller.activity_za_zone_entry_page(
            load=params,
            headers=header
        )

        # 步骤4: 验证响应码(只检查code字段)
        expected_code = step.get("expected_code", "IA0000")
        Assertion.str_assert(resp.json()["code"], expected_code)
        logging.info(f"响应码验证通过: {resp.json()['code']}")
        logging.info(f"响应数据: {resp.json()}")

    @allure.title("正常场景-未参与用户查询")
    @allure.story("用户状态查询")
    @pytest.mark.data('za_zone/entry_page_02_not_joined.yaml')
    @pytest.mark.P1
    def test_entry_page_02_not_joined(self, activity_sc, data):
        """
        测试场景: 未参与用户首次查询活动

        前置条件:
        - 用户未参与ZA Zone活动
        - 用户账号状态正常

        测试步骤:
        1. 构造未参与用户的请求参数
        2. 调用入口页查询接口
        3. 验证响应码为成功
        4. 验证返回引导信息

        预期结果:
        - code=IA0000
        - 返回活动引导信息
        - isJoined=false
        """
        step = data[0]

        user_id = step.get("user_id", "")
        header = {"userid": user_id, "language": "ca"}

        params = model.ActivityZaZoneEntryPage()
        params.json_data = {
            "customerNo": step.get("customer_no", "")
        }

        logging.info("测试未参与用户首次查询活动")
        resp = activity_sc.controller.activity_za_zone_entry_page(
            load=params,
            headers=header
        )

        expected_code = step.get("expected_code", "IA0000")
        Assertion.str_assert(resp.json()["code"], expected_code)
        logging.info(f"响应码验证通过: {resp.json()['code']}")

    @allure.title("边界场景-新注册用户")
    @allure.story("边界值测试")
    @pytest.mark.data('za_zone/entry_page_03_boundary.yaml')
    @pytest.mark.P1
    def test_entry_page_03_boundary(self, activity_sc, data):
        """
        测试场景: 刚完成注册的新用户首次查询

        前置条件:
        - 用户刚完成活动注册(注册时间<1分钟)
        - 用户数据可能未完全同步

        测试步骤:
        1. 构造新注册用户的请求参数
        2. 调用入口页查询接口
        3. 验证响应码为成功
        4. 验证返回初始状态

        预期结果:
        - code=IA0000
        - 返回初始化的用户状态
        - currentLevel=1, currentPoints=0
        """
        step = data[0]

        user_id = step.get("user_id", "")
        header = {"userid": user_id, "language": "ca"}

        params = model.ActivityZaZoneEntryPage()
        params.json_data = {
            "customerNo": step.get("customer_no", "")
        }

        logging.info("测试新注册用户首次查询")
        resp = activity_sc.controller.activity_za_zone_entry_page(
            load=params,
            headers=header
        )

        expected_code = step.get("expected_code", "IA0000")
        Assertion.str_assert(resp.json()["code"], expected_code)
        logging.info(f"响应码验证通过: {resp.json()['code']}")

    @allure.title("异常场景-客户不存在")
    @allure.story("异常处理")
    @pytest.mark.data('za_zone/entry_page_04_invalid.yaml')
    @pytest.mark.P2
    def test_entry_page_04_invalid(self, activity_sc, data):
        """
        测试场景: 使用不存在的客户编号查询

        测试步骤:
        1. 构造无效的customer_no
        2. 调用入口页查询接口
        3. 验证返回错误码

        预期结果:
        - code=400011 (客户不存在)
        - 返回错误提示信息
        """
        step = data[0]

        user_id = step.get("user_id", "9999999999999999")
        header = {"userid": user_id, "language": "ca"}

        params = model.ActivityZaZoneEntryPage()
        params.json_data = {
            "customerNo": step.get("customer_no", "INVALID_CUST_NOT_EXIST")
        }

        logging.info("测试客户不存在场景")
        resp = activity_sc.controller.activity_za_zone_entry_page(
            load=params,
            headers=header
        )

        # 验证错误码
        expected_code = step.get("expected_code", "400011")
        Assertion.str_assert(resp.json()["code"], expected_code)
        logging.info(f"错误码验证通过: {resp.json()['code']}")

    @allure.title("异常场景-缺少必填参数")
    @allure.story("异常处理")
    @pytest.mark.data('za_zone/entry_page_05_missing_param.yaml')
    @pytest.mark.P2
    def test_entry_page_05_missing_param(self, activity_sc, data):
        """
        测试场景: 缺少必填参数customer_no

        测试步骤:
        1. 构造缺少customer_no的请求
        2. 调用入口页查询接口
        3. 验证返回参数错误

        预期结果:
        - code=400001 (参数错误)
        - 提示缺少必填参数
        """
        step = data[0]

        user_id = step.get("user_id", "9999999999999999")
        header = {"userid": user_id, "language": "ca"}

        params = model.ActivityZaZoneEntryPage()
        params.json_data = {
            "customerNo": step.get("customer_no", "")  # 空值
        }

        logging.info("测试缺少必填参数场景")
        resp = activity_sc.controller.activity_za_zone_entry_page(
            load=params,
            headers=header
        )

        # 验证错误码
        expected_code = step.get("expected_code", "400001")
        Assertion.str_assert(resp.json()["code"], expected_code)
        logging.info(f"错误码验证通过: {resp.json()['code']}")
